Provider:
  Parameters: {loop: True}
  TFilters:
    - TFilter:
        Filters: [ CoefNpyTxtReader: {n_channels: 64}, ImageReader: ]
    - TFilter:
        Filters: [ Pass: , Sub: {val: 128} ]
    - TFilter:
        Filters: [ Pass: , Mul: {val: 0.004} ]
 
Processing:
  Parameters: {samples: 500, buffer_size: 50}
  TFilters:
    - TCropCoef8ImgFilter:
        Parameters: {size: 15}
        Filters: [LTCrop:, LTCrop: {scale: 8} ]
    - TFilter:
        Filters: [Label: {name: 'coef'}, Label: {name: 'label'}] 


Trainer:
  batch_size: 12
  max_iter: 250000
  caffe_mode: 'gpu'
  gpu_id: 0
  caffe_solverstate:
  caffe_weights: 
