Provider:
  Parameters: {loop: false}
  TFilters:
  - TFilter:
      Filters:
      - CoefNpyTxtReader: {n_channels: 128}
  - TFilter:
      Filters:
      - Label: {name: coef}
  - TFilter:
      Filters:
      - MullQuantTable:
#  - TFilter:
#      Filters:
#      - DecodeDCT: 
#  - TFilter:
#      Filters:
#      - Add: {val: 128} 
#  - TFilter:
#      Filters:
#      - Preview: {norm: 256} 
#  - TFilter:
#      Filters:
#      - Sub: {val: 128} 
#  - TFilter:
#      Filters:
#      - CodeDCT: 
  - TFilter:
      Filters:
      - Div: {val: 1024.}

provider_queue_size: 5

  
FCN:
  batch_size: 64
  patch_size: [20,20,64]
  borders: [1,1]
  in_blob: 'coef'
  out_blob: 'idct-sum-conv-5'
  caffe_mode: 'gpu'
  gpu_id: 0

