Train:
  Provider:
    Parameters: {loop: true}
    TFilters:
    - TFilter:
        Filters:
        - ImageX8Reader: {grayscale: True}
        - ImageX8Reader: {grayscale: True}
    - TFilter:
        Filters:
        - Sub: {val: 128}
        - Sub: {val: 128}
    - TFilter:
        Filters:
        - Mul: {val: 0.004}
        - Mul: {val: 0.004}
    - TFilter:
        Filters:
        - JPGBlockReshape:
        - JPGBlockReshape:
    - TFilter:
        Filters:
        - Label: {name: jpeg}
        - Label: {name: label}

  Sampler:
    Parameters: {buffer_size: 30, samples: 1000}
    TFilters:
    - TCropCoef8ImgFilter:
        Filters:
        - {LTCrop: null}
        - {LTCrop: null}
        Parameters: {crop_size: 8}
  provider_queue_size: 5
  sample_queue_size: 2048

Trainer:
  batch_size: 32
  max_iter: 250000
  caffe_mode: 'gpu'
  gpu_id: 0
  caffe_solverstate:
  caffe_weights:
  test_iter: 25
  test_interval: 500
  stat_interval: 10

