Process:
  -
    - FileListReader: {loop: False}
  -
    - ImageReader: {grayscale: True}
    - CoefNpyReader: {n_channels: 64}
  -
    - ShiftImg: {move_vec: [100, 100, 0]}
    - PadDCTMirror: { padding: [[0,0],[10,10]] }
  -
    - Pass:
    - DecodeDCT:
  -
    - Label: {name: "jpg"}
    - Label: {name: "dct"}
  -
    - Pass:
    - Mul: {val: 1024}
  -
    - Preview: {norm: 256, wait: 100}
    - Preview: {norm: 256, shift: 128}
