Process:
  -
    - FileListReader: {loop: False}
  -
    - ImageReader: {grayscale: True}
    - CoefNpyReader: {n_channels: 64}
  -
    - Sampler: {crop_size: 128, n_samples: 64, buffer_size: 3}
    - Sampler: {scale: 0.125, n_samples: 64, buffer_size: 3}
  # -
  #   - ShiftImg: {move_vec: [100, 100, 0]}
  #   - PadDCTMirror: { padding: [[0,0],[10,10]] }
  -
    - Pass:
    - DecodeDCT:
  -
    - Label: {name: "jpg"}
    - Label: {name: "dct"}
  -
    - Pass:
    - Mul: {val: 1024}
  -
    - Preview: {norm: 256, wait: 1}
    - Preview: {norm: 256, shift: 128, wait: 100}
